plan-player-analytics/Plan

- PlanPluginBridge/pom.xml
- PlanPluginBridge/src/main/java/com/djrapitops/pluginbridge/plan/advancedachievements/AdvancedAchievementsHook.java
Hello there!
This pull request updates the Advanced Achievements hook to use the new standalone API artifact. Note that doing so will only work with plugin versions 5.8.0 onwards, so you'll have to warn users in the update changelog. I could implement a workaround for the hook to work with 5.7.0+, but that will add quite a bit of code inside _AdvancedAchievementsHook_ (~15 lines). Let me know what you think!
Submitting the pull request to _master_ as there is no version specific branch yet. 😉 
Cheers,
Pyves
> Update Advanced Achievements hook

- Plan/dependency-reduced-pom.xml
- Plan/pom.xml
Updated shade exclusions, org.apache.logging should now be shady enough to work.
> Updated Maven Shade settings.

- Plan/pom.xml
- versions.txt
Hello there!
This pull request addresses #666. HikariCP relies on the SLF4J API for its logging, but you need to plug in an implementation (what SLF4J refers to as a "binding") at runtime for the logging to actually work.
I've selected the `slf4j-nop` as the implementation, in other words it suppresses the SLF4J logging, however other choices are also possible. 😉 
Cheers,
Pyves
> Fixed SLF4J startup warnings

- Plan/pom.xml
Since this plugin always generates one on compile, and since it's tracked in the git repo people have to revert their copy in order to pull changes.
> Don't create dependency-reduced-pom

- Plan/extensions/src/main/java/com/djrapitops/plan/extension/implementation/ExtensionRegister.java
CoreProtect API is not designed for fetching all events for a single player for a large time-span, so its usage is to be disabled until a solution can be figured out.
Affects issues:
- Close #1165
> Disabled CoreProtect Extension

- Plan/common/src/main/java/com/djrapitops/plan/settings/config/ConfigWriter.java
Currently, if the Plan directory is a symlink, `Files.createDirectories(outputPath.getParent());` fails, causing plan to fail to load. This adds a simple check to see if whatever is located at the Plan path is already a directory. 
Tested these expected cases: 
- Plan is symlink to directory: works
- Plan is missing: Creates dir, works
- Plan is empty directory: works
- Plan is existing directory: works
Also tested these unsupported cases:
- Plan is broken symlink: Plan fails to load with error
```
java.io.FileNotFoundException: Folders could not be created for config file /path/to/plugins/Plan/config.yml
```
- Plan is a file or a symlink to a file: Paper refuses to load the plugin with error
```
[01:33:20 ERROR]: Could not load 'plugins/Plan.jar' in folder 'plugins' …
```
> Allow Plan config directory to be a symlink

- Plan/common/src/main/resources/assets/plan/web/js/sessionAccordion.js
If Plan runs with a reverse proxy in sub route.
Player Page button and Server Analysis button on the Sessions page will not work.
It could be fixed by using relative path instead of absolute path on them.
> Use relative path in Player Page button and Server Analysis button

- Plan/common/src/main/resources/assets/plan/DefaultServerInfoFile.yml
Fix typo
`thread with caution`
to
`tread with caution`
in DefaultServerInfoFile.yml
> Fix typo in DefaultServerInfoFile.yml

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/RequestHandler.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/ResponseFactory.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/ResponseResolver.java
- Plan/common/src/main/resources/assets/plan/web/error.html
- Plan/common/src/main/resources/assets/plan/web/login.html
- Plan/common/src/main/resources/assets/plan/web/network.html
- Plan/common/src/main/resources/assets/plan/web/player.html
- Plan/common/src/main/resources/assets/plan/web/players.html
- Plan/common/src/main/resources/assets/plan/web/register.html
- Plan/common/src/main/resources/assets/plan/web/robots.txt
- Plan/common/src/main/resources/assets/plan/web/server.html
This PR fixes #1575 by adding a robots.txt file and the appropriate matching headers and meta tags to prevent indexing by search engines.
This is my first PR to this project and I'm still getting used to it, so let me know if you want anything changed!
> Disallow robots on Plan pages

- Plan/bukkit/src/main/java/com/djrapitops/plan/commands/use/BukkitPartBuilder.java
Fixes https://github.com/plan-player-analytics/Plan/issues/1600 by using `.append(TextComponent.fromLegacyText(...))` which is what the convenience method `.appendLegacy(...)` did
> Fix use of appendLegacy not working on 1.8

- Plan/api/src/main/java/com/djrapitops/plan/delivery/web/resolver/ResponseBuilder.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/ResponseResolver.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/ResponseSender.java
Just a small PR that fixes #1605 while I'm still getting used to contributing here. Removes the following warnings from the console:
```java
sendResponseHeaders: rCode = 204: forcing contentLen = -1
```
```java
sendResponseHeaders: being invoked with a content length for a HEAD request
```
I've tested it on a test server and everything works fine. The only thing to worry about is that there is no `Content-Length` header when sending a `HEAD` request, but according to [this StackOverflow answer](https://stackoverflow.com/a/42170178/6672199) including that header is optional.
After this I'm probably going to look at …
> Remove Content-Length related warnings from the server console

- Plan/common/src/main/resources/assets/plan/web/js/color-selector.js
This PR makes it so that this code in `theme.yml` enables night mode and sets the theme color to "plan" if night mode is disabled by the user:
```yml
DefaultColor: "night"
```
I'm not sure if this is the way you want default night mode to be enabled, but it is a really simple solution that works. It also looked like the default theme color in `theme.yml` didn't work at all, or at least it wasn't interpolated into `color-selector.js`, so this PR fixes that as well.
I've also finished #1318, so tell me if you want those changes on this PR or a separate one.
> Allow setting night mode (and other themes) by default in theme.yml

- Plan/common/src/main/resources/assets/plan/web/js/sb-admin-2.js
Fixes #1318 by using `history.replaceState` and preventing the default click event of most `<a>` tags instead of letting the default behavior occur and listening for the `hashchange` event.
We shouldn't have to worry about compatibility because the `history.replaceState` is [widely supported](https://caniuse.com/history) on all modern browsers.
> Prevent adding new history entries when switching tabs.

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/resources/assets/plan/web/js/xmlhttprequests.js
Reverts https://github.com/plan-player-analytics/Plan/commit/b7e1261597a81d7eb29d10059dc6d9ad13026b45 as of https://github.com/plan-player-analytics/Plan/issues/1425#issuecomment-708194444. There was a false positive rule from Easylist that was removed, so Brave and other adblockers no longer prevent the graph from working as intended.
And for future reference, if any functionality isn't working on Brave, feel free to reach out - we're not trying to break cool projects like this one :smile:
> Remove special error case for Brave browser

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/resources/assets/plan/locale/locale_DE.txt
Should I add myself to the `LangCode.java` file for this small fix?
This fixes a broken color code for the "Spielerzeit" (playtime) text in the `/plan ingame` output.
> locale: fix color code in german translation

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/resources/assets/plan/web/css/style.css
- Plan/common/src/main/resources/assets/plan/web/js/query.js
- Plan/common/src/main/resources/assets/plan/web/network.html
- Plan/common/src/main/resources/assets/plan/web/player.html
- Plan/common/src/main/resources/assets/plan/web/server.html
Quick & small pull that fixes the invalid centering of the page loader by adding a wrapper div for the icon & text and adjusting the CSS. Closes #1783.
Probably going to tackle some more of Plan's JS & HTML issues in the future, we'll see! I've really gotten into web development lately, and what's a better place to start contributing than a Finnish repo for a game I like! :)
> Fix invalid page loader centering

- Plan/common/src/main/resources/assets/plan/web/js/sb-admin-2.js
Correctly handle the URL hash when changing graph tabs. If a page is loaded but no page hash is supplied (`/network`), get current page hash from active navbar element. Hacky, but it works. Also got rid of jQuery for future-proofness. Fixes #1736.
> Fixed URL hash handling with graph tabs

- Plan/common/src/main/resources/assets/plan/web/css/style.css
- Plan/common/src/main/resources/assets/plan/web/js/network-values.js
- Plan/common/src/main/resources/assets/plan/web/network.html
Adds a list of servers to the navbar, fixes some irregularities with JS function names. The list shows about five servers by default before the scrollbar is shown. Text wrapping for long server names included.
Closes #1790.
Ref:
> Add a list of servers to the navbar

- Plan/common/src/main/java/com/djrapitops/plan/placeholder/PlayerPlaceHolders.java
- Plan/common/src/main/java/com/djrapitops/plan/placeholder/SessionPlaceHolders.java
Added raw time placeholders that just give you the raw ms value of any time based placeholder instead of the nicely formatted ones.
These placeholders can be more easily used to be processed in plugins that process placeholders (like scoreboards).
> Added "_raw" placeholder variants for further processing

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/resources/assets/plan/web/css/sb-admin-2.css
- Plan/common/src/main/resources/assets/plan/web/css/style.css
This pull request fixes the log-in screen logo being stretched on Safari.
> Fixes log-in logo being stretched on Safari

- Plan/build.gradle
- Plan/velocity/src/main/java/com/djrapitops/plan/PlanVelocity.java
- Plan/velocity/src/main/java/com/djrapitops/plan/commands/use/VelocityCMDSender.java
- Plan/velocity/src/main/java/com/djrapitops/plan/commands/use/VelocityCommand.java
- Plan/velocity/src/main/java/com/djrapitops/plan/commands/use/VelocityMessageBuilder.java
- Switched `VelocityCommand` implementation to `SimpleCommand` subinterface
- Removed old & deprecated `text` component handling API in favor of Adventure components
Tested working on Velocity 3.0.0, backwards compatibility tested on Velocity 1.1.8 (console only). Fixes #1957.
> Add Velocity 3.0.0 support

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/structure/TabsElement.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/pages/PlayerPluginTab.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/pages/ServerPluginTabs.java
Fixes #1982
Plugin ID is passed in together with `#getId()` to avoid it in every initializer to `Tab`. Clearly not the best solution but i wanted to make a contribution
> Use globally unique plugin ID for plugin cards with tabs

- Plan/api/src/main/java/com/djrapitops/plan/delivery/web/resolver/request/Request.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/RequestBodyConverter.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/RequestHandler.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/resolver/auth/LoginResolver.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/resolver/auth/RegisterResolver.java
- Plan/common/src/main/resources/assets/plan/web/js/xmlhttprequests.js
- Plan/common/src/main/resources/assets/plan/web/login.html
- Plan/common/src/main/resources/assets/plan/web/register.html
- Plan/common/src/test/java/com/djrapitops/plan/delivery/webserver/AccessControlTest.java
- Plan/common/src/test/java/com/djrapitops/plan/delivery/webserver/HttpsServerTest.java
May potentially alleviate some security concerns as query parameters are easy to log (such as in reverse proxy logs) and would previously contain cleartext passwords. Plus, logins "_traditionally_" use POST methods since the time of HTTP forms.
Since `x-www-form-urlencoded` is pretty much identical to query parameters which are parsed by the `URIQuery` class, i've used the same exact class to parse the form body.
This is a draft as
1. Only /auth/login is affected, this could probably be extended to other pages such as register (but it is easy to do so)
2. It may be incomplete
3. I don't even know if this is a desired change
Also, I understand that this change would probably be made obsolete by #1987
> Use POST method in requests such as login

- Plan/common/src/main/resources/assets/plan/bungeeconfig.yml
- Plan/common/src/main/resources/assets/plan/config.yml
The current buycraft link to find the secret key now goes to a 404 page. This PR updates it to their new tebex.io link, which is the first entry in the FAQ.
> Update secret key link for Buycraft

- Plan/common/src/main/java/com/djrapitops/plan/storage/database/MySQLDB.java
HikariCP's connectionTimeout defaults to 30 seconds, so at 10 minutes the connection leak detector will never trigger. Setting the threshold to 29 seconds makes the leak detector actually work.
> Lower MySQL leak detection threshold

- Plan/bukkit/src/main/java/com/djrapitops/plan/modules/bukkit/BukkitTaskModule.java
- Plan/bungeecord/src/main/java/com/djrapitops/plan/modules/bungee/BungeeTaskModule.java
- Plan/common/build.gradle
- Plan/common/src/main/java/com/djrapitops/plan/delivery/web/WebAssetVersionCheckTask.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/web/WebAssetVersions.java
- Plan/common/src/main/java/com/djrapitops/plan/storage/file/PlanFiles.java
- Plan/nukkit/src/main/java/com/djrapitops/plan/modules/nukkit/NukkitTaskModule.java
- Plan/sponge/src/main/java/com/djrapitops/plan/modules/sponge/SpongeTaskModule.java
- Plan/velocity/src/main/java/com/djrapitops/plan/modules/velocity/VelocityTaskModule.java
Closes #1995.
I am unsure if anything should be done differently, most notably [the actual warning part](https://github.com/rymiel/Plan/blob/67384e88a141811c4d318745cda35c9b2ca97aad/Plan/common/src/main/java/com/djrapitops/plan/delivery/web/WebAssetVersionCheckTask.java#L99-L108), like if it needs any special locale things, but the logic should mostly be there. When the [task itself is run](https://github.com/rymiel/Plan/blob/67384e88a141811c4d318745cda35c9b2ca97aad/Plan/common/src/main/java/com/djrapitops/plan/delivery/web/WebAssetVersionCheckTask.java#L65) could also probably be changed.
~~(and also i haven't tested it much)~~
> Notify about old versions of html customized files

- Plan/fabric/src/main/java/net/playeranalytics/plan/PlanFabric.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/commands/CommandManager.java
Oops. PlanSystem isn't initialized yet when the command manager is instantiated, hence throwing a NPE. Commands can't be run before the system is initialized so the new approach is safe.
> Fix getErrorLogger NPE on Fabric

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/velocity/src/main/java/com/djrapitops/plan/PlanVelocity.java
Added ViaVersion as an optional dependency on Velocity to allow the ViaVersion extension to correctly get ViaVersion API.
That fixes an issue where an error is thrown at startup saying that ViaVersion has not loaded the platform yet.
> Added ViaVersion as an optional dependency on Velocity

- Plan/build.gradle
- Plan/bukkit/src/main/java/com/djrapitops/plan/Plan.java
- Plan/bungeecord/src/main/java/com/djrapitops/plan/PlanBungee.java
- Plan/common/build.gradle
- Plan/common/src/main/java/com/djrapitops/plan/storage/upkeep/OldDependencyCacheDeletionTask.java
- Plan/gradle.properties
- Plan/nukkit/src/main/java/com/djrapitops/plan/PlanNukkit.java
- Plan/plugin/build.gradle
- Plan/sponge/src/main/java/com/djrapitops/plan/PlanSponge.java
- Plan/velocity/src/main/java/com/djrapitops/plan/PlanVelocity.java
This draft PR gives a quick example for implementing [SlimJar](https://github.com/slimjar/slimjar) as a runtime dependency downloader. Currently, only MySQL and SQLite are downloaded; this shrinks the filesize to under 10 megabytes, which should be plenty.
Draft, because there are a couple of big caveats with the plugin:
1) Logging isn't currently available without fiddling with the internal global logger's logging level (feature to supply our own logger coming in the future). On slower systems, this might falsely indicate that the server has crashed (when instead it's still processing the dependencies).
2) SlimJar …
> Implement SlimJar as a runtime dependency downloader

- .github/workflows/curseforge-upload.yml
Apparently `types: prerelease` doesn't trigger when a draft release is published as a prerelease.
> Fix Curseforge upload action

- Plan/velocity/src/main/java/com/djrapitops/plan/commands/use/VelocityCMDSender.java
The current system depends on mojang maintaining section signs for formatting which may be dropped any moment, a LegacyComponentSerializer turns the section-sign syntax into a proper Component
> Properly use a component serializer for VelocityCMDSender

- Plan/common/src/main/java/com/djrapitops/plan/storage/database/MySQLDB.java
I was able to make a make a test environment to test this, 
- Have MySQL enabled on Plan
- Have a server that is using `com.mysql.cj.jdbc.Driver`, and without `com.mysql.jdbc.Driver` (eg. Paper 1.16.5+)
+ Paper <1.16.5 and Spigot end up working as they (only) include the old driver
- Have a plugin trying to use mysql through the DriverManager, after Plan enables (and unregisters the new driver)
I was able to test that this fix worked in such a environment.
Fixes https://github.com/plan-player-analytics/Plan/issues/2147.
Sorry about the trouble this caused
> Fix for removing the wrong driver from the DriverManager

- Plan/common/src/main/resources/plugin.yml
add Votifier to Plugin.yml to stop error:
`[Plan] Loaded class com.vexsoftware.votifier.model.Vote from Votifier v2.7.3 which is not a depend, softdepend or loadbefore of this plugin.`
I haven't edited controbutors as this is such a minor change
> add Votifier to Plugin.yml

- Plan/common/src/main/resources/plugin.yml
When the Bukkit plugin is used on a server that also has AuthMe installed, a warning message is logged by the plugin manager. The warning correctly explains that although Plan references AuthMe at runtime, it is not a declared `depend`, `softdepend` or `loadbefore` type dependency.
The message is `[14:01:27] [Server thread/WARN]: [Plan] Loaded class fr.xephi.authme.api.v3.AuthMeApi from AuthMe v5.6.0-beta2-b2453 which is not a depend, softdepend or loadbefore of this plugin.`
> Added AuthMe to softdepend to disable a warning in Bukkit

- Plan/common/src/main/java/com/djrapitops/plan/exceptions/database/DBOpException.java
Adds a comment telling pterodactyl users what to do. I tested this with a large Plan database and increasing the default 100mb tmp size to 1024mb completely fixed any errors and Plan updated much quicker as you'd expect.
> Add comment about users that have pterodactyl

- Plan/fabric/build.gradle
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/listeners/fabric/ChatListener.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/identification/properties/FabricServerProperties.java
Mojang aims to release 1.19.3 on 6th of December, the latest release candidate will most likely be identical to the full release!
- Updates fabric module to 1.19.3 (and makes it backwards compatible, with at least 1.19.2)
- Prevents crashes if fabric-api mod is not present, but all required modules are present.
> update: Fabric 1.19.3 

- Plan/bukkit/src/main/java/com/djrapitops/plan/gathering/listeners/bukkit/PlayerOnlineListener.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
In some situations, the event.getHostname() will return exactly player's join adress without a port number, like `xxx.myserver.com`, so I add a condition check to prevent get that nonexistent ':' , to prevent the error like:
```
java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 14
java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) …
```
> Fix join address gathering

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/react/dashboard/src/components/extensions/ExtensionTable.jsx
Fix 'r.includes is not a function' on Litebans Kick Page ([#4169](https://github.com/plan-player-analytics/Plan/issues/4169))
This PR fixes a JavaScript runtime error on the LiteBans Kick page where `r.includes` would throw "is not a function." The issue was due to `r` not always being an array. The fix ensures `r` is an array before `.includes` is called, resolving the error that persisted across pages until refresh.
Tested on a local Plan instance: the error no longer appears and page navigation works as expected.
Thank you!
> V5.3.7 Bug Fix Fork - Litebans r.includes error
