- Plan/localization/locale_DE
Version 1.0.
Further optimisations may come if I find anything which can be formulated in a better way.
> Added a translation for the German language.

- .idea/libraries/Maven__com_destroystokyo_paper_paper_1_12_R0_1_SNAPSHOT.xml
- .idea/libraries/Maven__com_djrapitops_PlanPluginBridge_3_5_0.xml
- .idea/libraries/Maven__com_djrapitops_abstract_plugin_framework_2_0_0.xml
- Plan/pom.xml
- Plan/src/main/java/com/djrapitops/plan/ui/webserver/WebSocketServer.java
- Plan/src/main/java/com/djrapitops/plan/utilities/analysis/Analysis.java
- Plan/src/main/java/com/djrapitops/plan/utilities/analysis/MathUtils.java
- Plan/src/main/java/com/djrapitops/plan/utilities/uuid/UUIDUtility.java
- Plan/src/test/java/main/java/com/djrapitops/plan/utilities/FormatUtilsTest.java
Final PR for 3.5.5
Contains a fix for DecimalFormat for countries, which are using "," as the Decimal Format Symbol
Uses my Repository now to pull all dependencies -> Doesn't need manual dependency adding anymore
> Final PR for 3.5.5

- Plan/.idea/libraries/Maven__com_djrapitops_abstract_plugin_framework_2_0_2.xml
- Plan/src/main/java/com/djrapitops/plan/command/commands/ManageCommand.java
- Plan/src/main/java/com/djrapitops/plan/command/commands/manage/ManageDumpCommand.java
- Plan/src/main/java/com/djrapitops/plan/data/cache/queue/DataCacheClearQueue.java
- Plan/src/main/java/com/djrapitops/plan/data/cache/queue/DataCacheGetQueue.java
- Plan/src/main/java/com/djrapitops/plan/locale/Locale.java
- Plan/src/main/java/com/djrapitops/plan/ui/text/TextUI.java
- Plan/src/main/java/com/djrapitops/plan/utilities/analysis/Analysis.java
- Plan/src/main/java/com/djrapitops/plan/utilities/analysis/ExportUtility.java
- Plan/src/main/java/com/djrapitops/plan/utilities/file/dump/DumpLog.java
- Plan/src/main/java/com/djrapitops/plan/utilities/file/dump/DumpUtils.java
- Plan/src/main/resources/player.html
- Plan/src/test/java/utils/MockUtils.java
- PlanPluginBridge/pom.xml
- PlanPluginBridge/src/main/java/com/djrapitops/pluginbridge/plan/advancedachievements/AdvancedAchievementsAchievements.java
- PlanPluginBridge/src/main/java/com/djrapitops/pluginbridge/plan/askyblock/ASkyBlockIslandLevel.java
- PlanPluginBridge/src/main/java/com/djrapitops/pluginbridge/plan/essentials/EssentialsWarps.java
- PlanPluginBridge/src/main/java/com/djrapitops/pluginbridge/plan/factions/FactionsTable.java
- PlanPluginBridge/src/main/java/com/djrapitops/pluginbridge/plan/towny/TownyTable.java
- PlanPluginBridge/src/main/java/com/djrapitops/pluginbridge/plan/towny/TownyTown.java
Reverts Rsl1122/Plan-PlayerAnalytics#236
> Revert "PR for 3.6.3 (Fuzzlemann) (1)"

- .travis.yml
> Fixes travis issue with env variables on PRs

- README.md
added sponge link to ### Links
> Add sponge link to readme

- Plan/src/main/resources/locale/locale_DE.txt
Hi, I opened this PR to assist in the merge process @Morsemorse :)
> Pull request for German locale by Morsemorse

- Plan/src/main/resources/locale/locale_CN.txt
Updated Simplified Chinese language
> Updated Simplified Chinese language

- Plan/src/main/java/com/djrapitops/plan/system/tasks/BukkitTaskSystem.java
- Plan/src/main/java/com/djrapitops/plan/system/tasks/SpongeTaskSystem.java
- Plan/src/main/java/com/djrapitops/plan/system/tasks/server/PingCountTimerBukkit.java
- Plan/src/main/java/com/djrapitops/plan/system/tasks/server/PingCountTimerSponge.java
This is a implementation for Sponge ping measurement.
> Added PingCountTimerSponge

- Plan/src/main/java/com/djrapitops/plan/system/tasks/BungeeTaskSystem.java
- Plan/src/main/java/com/djrapitops/plan/system/tasks/server/PingCountTimerBungee.java
> Bungee pingAdded PinCoutTimerBungee

- Plan/src/main/resources/locale/locale_DE.txt
- versions.txt
If i find new mistakes I wanna fix it :)
> Fix mistake and little improve

- Plan/src/main/java/com/djrapitops/plan/PlanSponge.java
- Plan/src/main/resources/bungee.yml
- Plan/src/main/resources/plugin.yml
- PlanPluginBridge/pom.xml
- PlanPluginBridge/src/main/java/com/djrapitops/pluginbridge/plan/Bridge.java
- PlanPluginBridge/src/main/java/com/djrapitops/pluginbridge/plan/luckperms/LuckPermsData.java
- PlanPluginBridge/src/main/java/com/djrapitops/pluginbridge/plan/luckperms/LuckPermsHook.java
note, probably gonna add this to depends in plugin.ymls aswell as sponge 's @ Plugin (forgot this on nucleus too)
> LuckPerms Plugin Data

- Plan/src/main/resources/plugin.yml
- PlanPluginBridge/pom.xml
- PlanPluginBridge/src/main/java/com/djrapitops/pluginbridge/plan/Bridge.java
- PlanPluginBridge/src/main/java/com/djrapitops/pluginbridge/plan/discordsrv/DiscordSRVData.java
- PlanPluginBridge/src/main/java/com/djrapitops/pluginbridge/plan/discordsrv/DiscordSRVHook.java
DiscordSRV takes a while to load, so DiscordSRV#isReady returns false when at DiscordSRVHook#hook even though DiscordSRV is softdepended
> DiscordSRV plugin data

- .gitignore
- Plan/build.gradle
- Plan/bukkit/build.gradle
- Plan/bungeecord/build.gradle
- Plan/common/build.gradle
- Plan/plugin/build.gradle
- Plan/settings.gradle
- Plan/sponge/build.gradle
- Plan/velocity/build.gradle
Not actually fully functional, but it's a start. I don't think I can figure it all out on my own, but hopefully this much will give you enough of a start.
> Add WIP gradle build scripts

- .gitignore
- Plan/build.gradle
- Plan/bukkit/build.gradle
- Plan/bungeecord/build.gradle
- Plan/common/build.gradle
- Plan/common/src/test/java/utilities/dagger/PluginSuperClassBindingModule.java
- Plan/plugin/build.gradle
- Plan/settings.gradle
- Plan/sponge/build.gradle
- Plan/velocity/build.gradle
- scripts/runTests.sh
> Gradle setup

- .travis.yml
- Plan/build.gradle
- Plan/common/src/main/java/com/djrapitops/plan/data/store/containers/NetworkContainer.java
- Plan/common/src/main/java/com/djrapitops/plan/system/database/databases/sql/patches/KillsServerIDPatch.java
- Plan/common/src/main/java/com/djrapitops/plan/system/database/databases/sql/tables/WorldTimesTable.java
- Plan/common/src/main/resources/bungee.yml
- Plan/common/src/main/resources/plugin.yml
- Plan/common/src/main/resources/web/network.html
- Plan/common/src/main/resources/web/player.html
- Plan/common/src/main/resources/web/players.html
- Plan/common/src/main/resources/web/server.html
- Plan/sponge/src/main/java/com/djrapitops/plan/PlanSponge.java
- Plan/velocity/src/main/java/com/djrapitops/plan/PlanVelocity.java
- PlanPluginBridge/pom.xml
- PlanPluginBridge/src/main/java/com/djrapitops/pluginbridge/plan/litebans/LiteBansBukkitHook.java
- PlanPluginBridge/src/main/java/com/djrapitops/pluginbridge/plan/litebans/LiteBansBungeeHook.java
- PlanPluginBridge/src/main/java/com/djrapitops/pluginbridge/plan/litebans/LiteBansDatabaseQueries.java
This PR contains changes for version 4.6.2
> PR for 4.6.2

- Plan/common/src/main/java/com/djrapitops/plan/system/locale/lang/HealthInfoLang.java
- Plan/common/src/main/resources/locale/locale_CN.txt
- Plan/common/src/main/resources/locale/locale_CZ.txt
- Plan/common/src/main/resources/locale/locale_DE.txt
- Plan/common/src/main/resources/locale/locale_EN.txt
- Plan/common/src/main/resources/locale/locale_FI.txt
- Plan/common/src/main/resources/locale/locale_FR.txt
- Plan/common/src/main/resources/locale/locale_GA.txt
- Plan/common/src/main/resources/locale/locale_IT.txt
- Plan/common/src/main/resources/locale/locale_NL.txt
- Plan/common/src/main/resources/locale/locale_NO.txt
- Plan/common/src/main/resources/locale/locale_PL.txt
- Plan/common/src/main/resources/locale/locale_PT.txt
> Fixed downtime strings

- Plan/bukkit/src/main/java/com/djrapitops/plan/BukkitServerShutdownSave.java
- Plan/bukkit/src/main/java/com/djrapitops/plan/Plan.java
- Plan/bukkit/src/main/java/com/djrapitops/plan/PlanBukkitComponent.java
- Plan/bukkit/src/main/java/com/djrapitops/plan/modules/bukkit/BukkitSuperClassBindingModule.java
- Plan/bukkit/src/main/java/com/djrapitops/plan/system/tasks/BukkitTaskSystem.java
- Plan/bungeecord/src/main/java/com/djrapitops/plan/system/tasks/BungeeTaskSystem.java
- Plan/common/src/main/java/com/djrapitops/plan/ServerShutdownSave.java
- Plan/common/src/main/java/com/djrapitops/plan/ShutdownHook.java
- Plan/common/src/main/java/com/djrapitops/plan/db/SQLiteDB.java
- Plan/common/src/main/java/com/djrapitops/plan/system/cache/CacheSystem.java
- Plan/common/src/main/java/com/djrapitops/plan/system/cache/SessionCache.java
- Plan/common/src/main/java/com/djrapitops/plan/system/locale/lang/PluginLang.java
- Plan/common/src/main/java/com/djrapitops/plan/system/processing/Processing.java
- Plan/common/src/test/java/com/djrapitops/plan/ShutdownSaveTest.java
- Plan/common/src/test/java/extension/PrintExtension.java
- Plan/common/src/test/java/utilities/TestConstants.java
- Plan/common/src/test/java/utilities/TestResources.java
- Plan/common/src/test/java/utilities/mocks/Mocker.java
- Plan/sponge/src/main/java/com/djrapitops/plan/PlanSponge.java
- Plan/sponge/src/main/java/com/djrapitops/plan/PlanSpongeComponent.java
- Plan/sponge/src/main/java/com/djrapitops/plan/SpongeServerShutdownSave.java
- Plan/sponge/src/main/java/com/djrapitops/plan/modules/sponge/SpongeSuperClassBindingModule.java
- Plan/sponge/src/main/java/com/djrapitops/plan/system/listeners/SpongeListenerSystem.java
- Plan/sponge/src/main/java/com/djrapitops/plan/system/tasks/SpongeTaskSystem.java
- Plan/velocity/src/main/java/com/djrapitops/plan/system/tasks/VelocityTaskSystem.java
Reworked session save on server shutdown a little
> [#769] Session save on server shutdown

- Plan/build.gradle
- Plan/common/src/main/java/com/djrapitops/plan/data/store/containers/PerServerContainer.java
- Plan/common/src/main/java/com/djrapitops/plan/db/access/queries/containers/AllPlayerContainersQuery.java
- Plan/common/src/main/java/com/djrapitops/plan/db/access/queries/objects/WorldTimesQueries.java
- Plan/common/src/main/java/com/djrapitops/plan/utilities/html/graphs/special/WorldMap.java
- Plan/common/src/main/resources/bungee.yml
- Plan/common/src/main/resources/plugin.yml
- Plan/common/src/test/java/com/djrapitops/plan/db/CommonDBTest.java
- Plan/common/src/test/java/com/djrapitops/plan/db/MySQLTest.java
- Plan/common/src/test/java/com/djrapitops/plan/db/SQLiteTest.java
- Plan/common/src/test/java/com/djrapitops/plan/system/info/request/AnalysisExportTest.java
- Plan/common/src/test/java/com/djrapitops/plan/utilities/html/graphs/special/WorldMapTest.java
- Plan/sponge/src/main/java/com/djrapitops/plan/PlanSponge.java
- Plan/velocity/src/main/java/com/djrapitops/plan/PlanVelocity.java
- PlanPluginBridge/pom.xml
This PR contains changes for 4.7.1
> PR for 4.7.1

- Plan/build.gradle
- Plan/common/src/main/java/com/djrapitops/plan/system/file/PlanFiles.java
- Plan/common/src/main/java/com/djrapitops/plan/utilities/html/graphs/calendar/PlayerCalendar.java
- Plan/common/src/main/resources/assets/plan/web/server.html
- Plan/common/src/main/resources/bungee.yml
- Plan/common/src/main/resources/plugin.yml
- Plan/extensions/build.gradle
- Plan/sponge/src/main/java/com/djrapitops/plan/PlanSponge.java
- Plan/velocity/src/main/java/com/djrapitops/plan/PlanVelocity.java
- versions.txt
This PR contains changes for version 4.8.1
> PR for 4.8.1

- CONTRIBUTING.md
- Plan/common/src/main/resources/assets/plan/locale/locale_FR.txt
- versions.txt
This translation has been done by adapting the syntax to French language, so, the word order is sometimes different, it's "normal" that translations don't mean anything. Although I have worked for several weeks to adap to French as better as possible, it's possible that there are some mistakes made by me and I apologize for them. If that is the case, I'll correct them as soon as possible. Have a good time :)
> French Translation.

- PlanPluginBridge/src/main/java/com/djrapitops/pluginbridge/plan/viaversion/Protocol.java
Instead of "Newer than", it's more nice lol ^^.
> Add support of 1.14 with ViaVersion extension.

- Plan/api/src/main/java/com/djrapitops/plan/extension/extractor/ExtensionExtractor.java
- Plan/build.gradle
- Plan/common/src/main/java/com/djrapitops/plan/extension/ExtensionServiceImplementation.java
- Plan/common/src/main/resources/bungee.yml
- Plan/common/src/main/resources/plugin.yml
- Plan/extensions/src/main/java/com/djrapitops/plan/extension/implementation/ExtensionRegister.java
- Plan/sponge/src/main/java/com/djrapitops/plan/PlanSponge.java
- Plan/velocity/src/main/java/com/djrapitops/plan/PlanVelocity.java
> PR for 4.9.1

- Jenkinsfile
Added a Jenkins configuration file for a build pipeline using gradle.
- Runs tests
- Run checkstyle
- Runs sonar and publishes to SonarCloud
Affects issues:
- #926
New issues will be opened for MySQL and Selenium tests on Jenkins since they require some additional changes in the code.
> Configured Jenkins

- Plan/bukkit/src/main/java/com/djrapitops/plan/system/listeners/bukkit/DeathEventListener.java
- Plan/common/src/main/java/com/djrapitops/plan/data/store/mutators/ActivityIndex.java
- Plan/common/src/main/java/com/djrapitops/plan/db/access/queries/objects/UserIdentifierQueries.java
- Plan/common/src/main/java/com/djrapitops/plan/db/tasks/KeepAliveTask.java
- Plan/common/src/main/java/com/djrapitops/plan/system/info/InfoSystem.java
- Plan/common/src/main/java/com/djrapitops/plan/system/webserver/response/ResponseFactory.java
- Plan/common/src/main/java/com/djrapitops/plan/utilities/html/HtmlStructure.java
- Plan/common/src/main/java/com/djrapitops/plan/utilities/html/graphs/line/Line.java
- Plan/common/src/main/java/com/djrapitops/plan/utilities/html/graphs/stack/ActivityStackGraph.java
- Plan/common/src/test/java/com/djrapitops/plan/data/store/mutators/TPSMutatorTest.java
- Plan/common/src/test/java/utilities/OptionalAssert.java
- Plan/common/src/test/java/utilities/RandomData.java
- Plan/common/src/test/java/utilities/TestConstants.java
- Plan/common/src/test/java/utilities/TestData.java
- Plan/common/src/test/java/utilities/TestDatabaseCreator.java
- Plan/config/checkstyle/checkstyle.xml
Modified checkstyle ruleset to pass current files, and fixing some minor check issues when only few were present.
The length rules should be tightened when possible - especially the line length, which is at 3000 due to all countries being inline in `WorldMap`
Consideration was made to move the country names and codes to a .csv file in the future.
> Enforced some upper-limit checkstyle rules

- Plan/build.gradle
- Plan/bukkit/src/main/java/com/djrapitops/plan/system/listeners/bukkit/AFKListener.java
- Plan/common/src/main/java/com/djrapitops/plan/db/access/transactions/Transaction.java
- Plan/common/src/main/java/com/djrapitops/plan/system/afk/AFKTracker.java
- Plan/common/src/main/java/com/djrapitops/plan/system/cache/SessionCache.java
- Plan/common/src/main/java/com/djrapitops/plan/utilities/file/FileWatcher.java
- Plan/common/src/main/resources/bungee.yml
- Plan/common/src/main/resources/plugin.yml
- Plan/common/src/test/java/com/djrapitops/plan/db/H2Test.java
- Plan/common/src/test/java/com/djrapitops/plan/db/MySQLTest.java
- Plan/common/src/test/java/com/djrapitops/plan/db/SQLiteTest.java
- Plan/sponge/src/main/java/com/djrapitops/plan/PlanSponge.java
- Plan/sponge/src/main/java/com/djrapitops/plan/system/listeners/sponge/SpongeAFKListener.java
- Plan/velocity/src/main/java/com/djrapitops/plan/PlanVelocity.java
Changes between versions 4.9.3 -> 4.9.4
> PR for version 4.9.4

- Plan/common/src/main/resources/assets/plan/locale/locale_FR.txt
Small fixes of old translations (better sense and understanding).
Enjoy :)
> French Translation updated for Interface-redesign

- Plan/common/src/main/resources/assets/plan/locale/locale_JA.txt
~~Please don't merge because it is still being translated.~~
> Update locale_JA.txt for v5.0Dev(Translation completed)

- Plan/common/src/main/java/com/djrapitops/plan/extension/ExtensionServiceImplementation.java
- Plan/common/src/main/java/com/djrapitops/plan/extension/implementation/CallerImplementation.java
- Plan/extensions/build.gradle
Changed Caller.updatePlayer to not throw exception on null variables.
Also updated DKBasn Extension to not call the updater with a null UUID
> Extensions Caller change

- Plan/common/src/main/java/com/djrapitops/plan/settings/config/changes/ConfigChange.java
- Plan/common/src/main/java/com/djrapitops/plan/settings/config/changes/ConfigUpdater.java
- Plan/common/src/main/resources/assets/plan/bungeeconfig.yml
- Plan/common/src/main/resources/assets/plan/config.yml
This comment was causing confusion (The comment is out of date)
From discord:
> "If you're running Plan with Bungee, the internal WebServer is required for communication between Bukkit & Bungee and should not be disabled"
So, should I NOT disabled WebServer AT ALL, or could I safely disable it among the Bukkit servers?
> Removed comment from Webserver.Disable_Webserver

- Plan/common/src/main/java/com/djrapitops/plan/settings/config/ConfigWriter.java
- Plan/common/src/main/resources/assets/plan/web/error.html
- Plan/common/src/main/resources/assets/plan/web/network.html
- Plan/common/src/main/resources/assets/plan/web/player.html
- Plan/common/src/main/resources/assets/plan/web/players.html
- Plan/common/src/main/resources/assets/plan/web/server.html
> Symlink config dir by Combustible

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/pages/NetworkPage.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/pages/PlayerPage.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/pages/PlayersPage.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/pages/ServerPage.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/response/errors/ErrorResponse.java
- Plan/common/src/main/java/com/djrapitops/plan/settings/locale/LangCode.java
- Plan/common/src/main/resources/assets/plan/locale/locale_FR.txt
- Plan/common/src/main/resources/assets/plan/web/error.html
- Plan/common/src/main/resources/assets/plan/web/network.html
- Plan/common/src/main/resources/assets/plan/web/player.html
- Plan/common/src/main/resources/assets/plan/web/players.html
- Plan/common/src/main/resources/assets/plan/web/server.html
Finalize #1309 by adding missing suggestion and by adding Nogapra to Contributors
> Locale FR updated by Nogapra (#1309)

- .github/workflows/gradle.yml
- Plan/common/src/test/java/utilities/CIProperties.java
- Plan/common/src/test/java/utilities/DBPreparer.java
Ensures that MySQL tests are run on every commit
> Added MySQL to Github Actions

- Plan/common/src/main/resources/assets/plan/locale/locale_RU.txt
> locale_RU.txt

- Plan/common/src/main/resources/assets/plan/web/error.html
- Plan/common/src/main/resources/assets/plan/web/js/color-selector.js
- Plan/common/src/main/resources/assets/plan/web/login.html
- Plan/common/src/main/resources/assets/plan/web/network.html
- Plan/common/src/main/resources/assets/plan/web/player.html
- Plan/common/src/main/resources/assets/plan/web/players.html
- Plan/common/src/main/resources/assets/plan/web/register.html
- Plan/common/src/main/resources/assets/plan/web/server.html
I was thinking why shouldn't we have more colors on the dark mode so I tried to make changes and I know these changes aren't perfect but should give a good presentation on what I had in mind XD I am horrible at JS 
https://i.imgur.com/riTlPTg.png
> Suggestion about web ui

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/java/com/djrapitops/plan/settings/locale/LangCode.java
- Plan/common/src/main/resources/assets/plan/locale/locale_CN.txt
Got these changes via Spigot conversation
@f0rb1d or @qsefthuopq, would you mind reviewing the changes?
----
If you haven't reviewed on github before, go to the files changed tab and click on lines to add comments. After reviewing you can submit the review at the top right corner with the review button
> Chinese locale update by shaokeyibb

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/ResponseFactory.java
- Plan/common/src/main/java/com/djrapitops/plan/settings/locale/TranslatedString.java
- Plan/common/src/main/resources/assets/plan/locale/locale_CN.txt
- Plan/common/src/main/resources/assets/plan/web/error.html
- Plan/common/src/main/resources/assets/plan/web/network.html
- Plan/common/src/main/resources/assets/plan/web/player.html
- Plan/common/src/main/resources/assets/plan/web/players.html
- Plan/common/src/main/resources/assets/plan/web/server.html
- Fix translate key of `Plan Wiki, Tutorials & Documentation` not work
- Fix http link translated.
> Some fix of website

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/java/com/djrapitops/plan/settings/locale/LangCode.java
> Elquerro to contributors

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/java/com/djrapitops/plan/settings/locale/LangCode.java
- Plan/common/src/main/resources/assets/plan/locale/locale_ES.txt
> Spanish locale update by Elguerrero

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/java/com/djrapitops/plan/settings/locale/LangCode.java
- Plan/common/src/main/resources/assets/plan/locale/locale_IT.txt
This fixes some mispronunciations on the locale and adds more translations
> Update Italian locale and fix some errors :3

- Plan/common/src/main/resources/assets/plan/locale/locale_CS.txt
Just a translation for Plan, Czech language, by me of course.
> Creating a new localization for Czech language

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/java/com/djrapitops/plan/settings/locale/LangCode.java
- Plan/common/src/main/resources/assets/plan/locale/locale_KO.txt
Adds Korean locale by Guinness_Akihiko
> Korean Locale by Guinness_Akihiko

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
Signed-off-by: Alexander Trost <galexrt@googlemail.com>
This fixes the contributors list missing a comma. Sorry about that..
I broke this in #1684.
> contributors: fix the contributors list commas

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/java/com/djrapitops/plan/settings/locale/LangCode.java
- Plan/common/src/main/resources/assets/plan/locale/locale_CS.txt
- all rows are translated
- fixed weird translations
- Found BUG: missing keys for texts in server's insights (average chunks, average entities)
> Improved Czech translation

- Plan/build.gradle
- Plan/bukkit/src/main/java/com/djrapitops/plan/Plan.java
- Plan/bungeecord/src/main/java/com/djrapitops/plan/PlanBungee.java
- Plan/common/build.gradle
- Plan/common/src/main/java/com/djrapitops/plan/DependencyStartup.java
- Plan/nukkit/src/main/java/com/djrapitops/plan/PlanNukkit.java
- Plan/plugin/build.gradle
- Plan/sponge/src/main/java/com/djrapitops/plan/PlanSponge.java
- Plan/velocity/src/main/java/com/djrapitops/plan/PlanVelocity.java
This PR contains changes for downloading dependencies at runtime, mainly the 3 database drivers that take up 60% of the jar.
Related issue #1759
> Dependency downloading

- Plan/build.gradle
- Plan/nukkit/build.gradle
- Plan/nukkit/src/main/java/com/djrapitops/plan/addons/placeholderapi/NukkitPlaceholderRegistrar.java
Update nukkit module to PlaceholderAPI 1.4
Thank you!
> Update nukkit module to support new PlaceholderAPI version

- Plan/common/src/main/resources/assets/plan/locale/locale_DE.txt
Updated the german locale file a bit.
> [DE] Updated language file

- Plan/common/src/main/resources/assets/plan/locale/locale_TR.txt
> Update locale_TR.txt part 1

- Plan/common/src/main/resources/assets/plan/locale/locale_TR.txt
> Update locale_TR.txt part 2

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/java/com/djrapitops/plan/settings/locale/LangCode.java
- Plan/common/src/main/resources/assets/plan/locale/locale_TR.txt
Apply translations to turkish locale
> Turkish locale updated by BruilsiozPro

- Plan/gradle/wrapper/gradle-wrapper.properties
Changed to the bin distribution.
That is *significantly* smaller to download. And devs don't need the docs locally.
> Changed to the bin distribution

- Plan/bukkit/src/main/java/com/djrapitops/plan/addons/placeholderapi/PlanPlaceholderExtension.java
Add offline player support for PAPI
Fixes #1854
> Add offline player support for PAPI

- Plan/bukkit/src/main/java/com/djrapitops/plan/addons/placeholderapi/PlanPlaceholderExtension.java
If not null, add to cache; if null, don't. This fix makes `onPlaceholderRequest()` return null, which is intended if an invalid placeholder is given.
Quick test shows this working, shouldn't have any issues.
> Fix NPE with invalid placeholders

- Plan/build.gradle
Reverts plan-player-analytics/Plan#1878
> Revert "Bump caffeine from 2.8.0 to 3.0.2 in /Plan"

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/java/com/djrapitops/plan/settings/locale/LangCode.java
- Plan/common/src/main/resources/assets/plan/locale/locale_CN.txt
The current Simplified Chinese translation contains a lot of errors and deficiencies. Obviously, the previous translators did not translate according to context. Now I have retranslated all the text and made sure it is correct on my Network.
Please note that due to some differences between Chinese and English itself, some sentences cannot be completely translated correctly. And some values cannot be read correctly, such as `HTML - TOTAL_AFK || 总挂机时长` will display as ` Total 挂机`. So I can’t make sure that the translation is 100% accurate.
In addition, please consider using programs like crowdin.com to provide …
> Update simplified Chinese translation

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/java/com/djrapitops/plan/settings/locale/LangCode.java
- Plan/common/src/main/resources/assets/plan/locale/locale_NL.txt
Add support for the Dutch (NL) (Nederlands) language to Plan.
> Add Dutch translations

- Plan/api/src/main/java/com/djrapitops/plan/extension/builder/ValueBuilder.java
- Plan/bukkit/src/main/java/com/djrapitops/plan/addons/placeholderapi/PlanPlaceholderExtension.java
- Plan/common/src/main/java/com/djrapitops/plan/commands/PlanCommand.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/java/com/djrapitops/plan/settings/locale/Locale.java
PR contains fixing some of sonarcloud issues.
The Pattern.compile one was [the security issue](https://sonarcloud.io/project/security_hotspots?id=com.djrapitops%3APlan), others were code smell issues.
Also, the Pattern.compile issue improves the performance.
> Fix some of sonarcloud issues.

- Plan/sponge/build.gradle
- Plan/velocity/build.gradle
Bumps Blossom to 1.3.0 and fixes the build error associated with the version bump.
> Bump Blossom to 1.3.0 & fix build error

- Plan/build.gradle
Dumbendabot doesn't seem to care about minor versions anymore 😄
> Bump caffeine from 2.8.0 to 2.9.2

- Plan/common/src/main/resources/assets/plan/web/register.html
> Fix registration finish modal not displaying

- Plan/api/src/main/java/com/djrapitops/plan/delivery/web/resolver/request/URIQuery.java
- Plan/bukkit/src/main/java/com/djrapitops/plan/BukkitServerShutdownSave.java
- Plan/bukkit/src/main/java/com/djrapitops/plan/gathering/timed/BukkitPingCounter.java
- Plan/bukkit/src/main/java/com/djrapitops/plan/gathering/timed/PingMethodReflection.java
- Plan/bukkit/src/main/java/com/djrapitops/plan/gathering/timed/ReflectiveLatencyFieldMethod.java
- Plan/bukkit/src/main/java/com/djrapitops/plan/gathering/timed/ReflectiveLevelEntityPlayerLatencyFieldMethod.java
- Plan/bukkit/src/main/java/com/djrapitops/plan/gathering/timed/ReflectivePingFieldMethod.java
- Plan/bukkit/src/main/java/com/djrapitops/plan/gathering/timed/ReflectiveUnmappedLatencyFieldMethod.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/resolver/json/ErrorsJSONResolver.java
- Plan/common/src/test/java/com/djrapitops/plan/gathering/domain/ActiveSessionTest.java
Cleaned up some new sonar smells
> Sonar cleanup for new smells

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/java/com/djrapitops/plan/settings/locale/LangCode.java
- Plan/common/src/main/resources/assets/plan/locale/locale_RU.txt
> Upgrade russian translation

- Plan/common/src/main/java/com/djrapitops/plan/delivery/domain/mutators/TPSMutator.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/export/NetworkPageExporter.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/json/JSONFactory.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/json/graphs/GraphJSONCreator.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/cache/AsyncJSONResolverService.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/cache/DataID.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/resolver/json/GraphsJSONResolver.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/resolver/json/NetworkJSONResolver.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/resolver/json/NetworkPerformanceJSONResolver.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/resolver/json/PlayerKillsJSONResolver.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/resolver/json/PlayersTableJSONResolver.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/resolver/json/SessionsJSONResolver.java
- Plan/common/src/main/java/com/djrapitops/plan/gathering/domain/TPS.java
- Plan/common/src/main/java/com/djrapitops/plan/identification/Identifiers.java
- Plan/common/src/main/java/com/djrapitops/plan/storage/database/queries/objects/TPSQueries.java
- Plan/common/src/main/java/com/djrapitops/plan/storage/database/sql/tables/ServerTable.java
- Plan/common/src/main/resources/assets/plan/web/js/network-values.js
- Plan/common/src/main/resources/assets/plan/web/js/server-values.js
- Plan/common/src/main/resources/assets/plan/web/js/xmlhttprequests.js
- Plan/common/src/main/resources/assets/plan/web/network.html
- Plan/common/src/test/java/com/djrapitops/plan/delivery/webserver/AccessControlTest.java
Contains a new feature, network performance tab
> Network performance tab

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/resources/assets/plan/web/player.html
Uses helm (layered heads) avatars instead of boring old normal basic ones.
> Helm heads

- Plan/build.gradle
- Plan/common/src/main/java/com/djrapitops/plan/PlanSystem.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/json/JSONFactory.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/json/ServerOverviewJSONCreator.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/json/network/NetworkOverviewJSONCreator.java
- Plan/common/src/main/java/com/djrapitops/plan/gathering/ServerUptimeCalculator.java
- Plan/common/src/main/java/com/djrapitops/plan/settings/locale/lang/HtmlLang.java
- Plan/common/src/main/java/com/djrapitops/plan/storage/database/queries/QueryAPIQuery.java
- Plan/common/src/main/java/com/djrapitops/plan/storage/database/queries/QueryStatement.java
- Plan/common/src/main/java/com/djrapitops/plan/storage/database/queries/objects/TPSQueries.java
- Plan/common/src/main/resources/assets/plan/web/js/network-values.js
- Plan/common/src/main/resources/assets/plan/web/js/server-values.js
- Plan/common/src/main/resources/assets/plan/web/network.html
- Plan/common/src/main/resources/assets/plan/web/server.html
- Plan/common/src/test/java/com/djrapitops/plan/storage/database/queries/TPSQueriesTest.java
- Plan/nukkit/build.gradle
This PR contains a new feature, server uptime #1845
> Added server uptime

- Plan/bukkit/src/main/java/com/djrapitops/plan/gathering/listeners/bukkit/DeathEventListener.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/domain/PlayerIdentifier.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/domain/ServerIdentifier.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/domain/mutators/PlayerKillMutator.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/domain/mutators/SessionsMutator.java
- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/json/graphs/calendar/PlayerCalendar.java
- Plan/common/src/main/java/com/djrapitops/plan/gathering/domain/PlayerKill.java
- Plan/common/src/main/java/com/djrapitops/plan/gathering/domain/PlayerKills.java
- Plan/common/src/main/java/com/djrapitops/plan/identification/ServerInfo.java
- Plan/common/src/main/java/com/djrapitops/plan/processing/processors/player/PlayerKillProcessor.java
- Plan/common/src/main/java/com/djrapitops/plan/storage/database/queries/objects/KillQueries.java
- Plan/common/src/main/java/com/djrapitops/plan/storage/database/queries/objects/SessionQueries.java
- Plan/common/src/main/java/com/djrapitops/plan/storage/database/sql/tables/KillsTable.java
- Plan/common/src/main/resources/assets/plan/web/js/sessionAccordion.js
- Plan/common/src/test/java/com/djrapitops/plan/gathering/domain/PlayerKillTest.java
- Plan/common/src/test/java/com/djrapitops/plan/gathering/domain/SessionTest.java
- Plan/common/src/test/java/com/djrapitops/plan/gathering/importing/data/ImportBuilderTest.java
- Plan/common/src/test/java/utilities/RandomData.java
- Plan/common/src/test/java/utilities/TestData.java
- Plan/nukkit/src/main/java/com/djrapitops/plan/gathering/listeners/nukkit/DeathEventListener.java
- Plan/sponge/src/main/java/com/djrapitops/plan/gathering/listeners/sponge/SpongeDeathListener.java
This PR adds server name to all kill lists #1437
> Add server name to kill lists

- Plan/common/src/main/resources/assets/plan/web/js/query.js
> Add nightmode undefined check for query graphs

- Plan/common/src/main/java/com/djrapitops/plan/modules/FiltersModule.java
- Plan/common/src/main/java/com/djrapitops/plan/storage/database/queries/filter/filters/PluginBooleanGroupFilter.java
- Plan/common/src/main/java/com/djrapitops/plan/storage/database/queries/objects/ServerQueries.java
- Plan/common/src/main/java/com/djrapitops/plan/utilities/java/Maps.java
- Plan/common/src/main/resources/assets/plan/web/js/filters.js
> Implemented a PluginBooleanGroupFilter

- .github/workflows/gradle.yml
> Disable shallow clone on actions checkout

- .github/workflows/javadocs.yml
> Use Java 16 when deploying javadocs

- Plan/fabric/src/main/java/net/playeranalytics/plan/PlanFabric.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/identification/properties/FabricServerProperties.java
i forgot to give dagger a thing so it became mad at me
> Fix ServerProperties binding

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/java/com/djrapitops/plan/settings/locale/LangCode.java
- Plan/common/src/main/resources/assets/plan/locale/locale_ZH_TW.txt
> Update zh_TW translation

- .github/workflows/curseforge-upload.yml
We'll have to make a release and see if this works :D
> Add CurseForge upload workflow

- Plan/common/src/main/resources/assets/plan/web/js/graphs.js
- Plan/common/src/main/resources/assets/plan/web/network.html
- Plan/common/src/main/resources/assets/plan/web/server.html
Implements javascript code that averages player count and displays it on the players online graph
I was unable to test this properly due to lack of data.
#1796
> Added javascript that calculates average players online for the graph

- Plan/common/src/main/resources/assets/plan/web/js/loadErrors.js
- Plan/common/src/main/resources/assets/plan/web/js/player-values.js
- Plan/common/src/main/resources/assets/plan/web/js/sessionAccordion.js
- Plan/common/src/main/resources/assets/plan/web/network.html
- Plan/common/src/main/resources/assets/plan/web/player.html
- Plan/common/src/main/resources/assets/plan/web/server.html
Should fix #2063 along with some other stuff.
> Fix remaining Bootstrap data attributes

- Plan/fabric/build.gradle
- Plan/fabric/src/main/java/net/playeranalytics/plan/PlanFabric.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/FabricSensor.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/identification/properties/FabricServerProperties.java
- Plan/fabric/src/main/java/net/playeranalytics/plugin/FabricPlatformLayer.java
- Plan/fabric/src/main/java/net/playeranalytics/plugin/FabricPluginInformation.java
- Plan/fabric/src/main/java/net/playeranalytics/plugin/server/FabricPluginLogger.java
Fixes some minor bugs on Fabric & makes console output look nicer.
> Fabric fixes

- .github/workflows/curseforge-upload.yml
> Fix download URL in CF upload workflow

- .github/workflows/curseforge-upload.yml
> Use correct release type for CF upload

- Plan/velocity/src/main/java/com/djrapitops/plan/PlanVelocity.java
Fixes #2092, tested working on Velocity 3.0.1.
> Don't reload dependencies when reloading plugin

- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/listeners/events/mixin/ServerPlayerEntityMixin.java
> Correctly log fabric deaths where killer is null

- .github/workflows/curseforge-upload.yml
> Add 1.18.x support in Curseforge upload workflow

- Plan/common/src/main/resources/assets/plan/locale/locale_RU.txt
> Update RU locale

- .github/workflows/gradle-pr.yml
- .github/workflows/gradle.yml
Sets up selenium for unit tests for #2290
> Add selenium setup to workflow

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/java/com/djrapitops/plan/settings/locale/LangCode.java
- Plan/common/src/main/resources/assets/plan/locale/locale_FI.yml
Fixed compound word in finnish locale file. Small change, but this hurt my head.
Thank you!
> Fix typo in finnish locale

- .github/workflows/gradle-pr.yml
- .github/workflows/gradle.yml
- .github/workflows/javadocs.yml
- .gitignore
- Plan/build.gradle
- Plan/common/build.gradle
- Plan/fabric/build.gradle
- Plan/fabric/src/main/java/net/playeranalytics/plan/PlanFabric.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/commands/CommandManager.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/commands/use/FabricMessageBuilder.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/listeners/events/mixin/EntityMixin.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/listeners/events/mixin/PlayerEntityMixin.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/listeners/events/mixin/ServerCommandSourceMixin.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/listeners/events/mixin/ServerPlayNetworkHandlerMixin.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/listeners/fabric/ChatListener.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/listeners/fabric/DeathEventListener.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/listeners/fabric/GameModeChangeListener.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/listeners/fabric/PlayerOnlineListener.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/listeners/fabric/WorldChangeListener.java
- Plan/fabric/src/main/resources/fabric.mod.json
- Plan/fabric/src/main/resources/plan.mixins.json
- Plan/gradle/wrapper/gradle-wrapper.properties
- Plan/settings.gradle
Updates fabric module to support Minecraft 1.19
> Fabric 1.19

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- README.md
Fixed grammar mistakes in README.MD.
> Fixed grammer mistakes in README.MD

- Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/http/JettyWebserver.java
- Plan/common/src/main/java/com/djrapitops/plan/extension/ExtensionSvc.java
- Plan/common/src/main/java/com/djrapitops/plan/gathering/domain/event/JoinAddress.java
- Plan/common/src/main/java/com/djrapitops/plan/gathering/events/PlayerLeaveEventConsumer.java
- Plan/common/src/main/java/com/djrapitops/plan/storage/database/queries/LargeStoreQueries.java
- Plan/common/src/test/java/com/djrapitops/plan/storage/database/queries/JoinAddressQueriesTest.java
- Fixed extensions with PLAYER_LEAVE not getting updated
- Fixed data truncation for join address
> Bugfixes to build 1951

- Plan/common/src/main/resources/assets/plan/locale/locale_DE.yml
Added translation of many descriptions.
> Update translation of locale_DE.yml

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/java/com/djrapitops/plan/settings/locale/LangCode.java
- Plan/common/src/main/resources/assets/plan/locale/locale_DE.yml
Combined commits from PRs #2632 #2633 #2634
> DE Locale update by DubHacker

- Plan/common/build.gradle
- Plan/common/src/main/java/com/djrapitops/plan/storage/database/SQLDB.java
- Plan/sponge/build.gradle
Change the scope of `mixin` to compileOnly as it is provided by sponge and including it in the jar is incorrect, removes `junit` from being a included by `json-simple`.
Also corrects logging for errors with dependency downloading, `download` returns a CompletableFuture for each dependency (or I should say at least one but up-to as many as are given 😅) instead of repository. 
So I switched it to using `downloadAll` which returns a single CompletableFuture with the result of all dependencies combined, the error looks like something like this,
```java
...
Caused by: java.lang.RuntimeException: Failed to download …
```
> A few small cleanup items

- .github/workflows/ci.yml
- .github/workflows/on-release.yml
Updates checkout, setup-java and upload-artifact versions to v3
Related to:
- #2676
> Update action versions

- Plan/build.gradle
- Plan/fabric/build.gradle
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/domain/FabricPlayerData.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/listeners/events/mixin/ClientToServerHandshakePacketMixin.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/listeners/events/mixin/ServerPlayerEntityMixin.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/listeners/fabric/ChatListener.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/listeners/fabric/DeathEventListener.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/listeners/fabric/FabricAFKListener.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/listeners/fabric/GameModeChangeListener.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/listeners/fabric/PlayerOnlineListener.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/listeners/fabric/WorldChangeListener.java
- Plan/fabric/src/main/resources/plan.mixins.json
Updates fabric module to 1.19.4 support, dropping compatibility with older versions. Runs fine, didn't test data gathering though.
> Fabric 1.19.4 compatibility

- Plan/fabric/src/main/resources/fabric.mod.json
Fixes #2969
-----
JAR: https://github.com/plan-player-analytics/Plan/suites/12143930110/artifacts/640446401
> Fix incorrect networking API declaration in fabric module

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/java/com/djrapitops/plan/settings/locale/LangCode.java
- Plan/common/src/main/resources/assets/plan/locale/locale_JA.yml
close #3074 
Fixed a Japanese language error reported in #3074.
> Fix Japanese translation

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/sponge/build.gradle
Adjust blank optional dependency versions to `"*"` to allow any version on SpongeForge
- Fixes #3144
> [Sponge] Dependency version issue

- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/fabric/build.gradle
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/FabricSensor.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/domain/FabricPlayerData.java
- Plan/fabric/src/main/java/net/playeranalytics/plan/gathering/listeners/events/mixin/ServerCommandSourceMixin.java
Updated the modification to support Fabric on 1.20.4. Tested on our own server.
> Fabric 1.20.4

- Plan/build.gradle
- Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java
- Plan/common/src/main/resources/plugin.yml
- Plan/extensions/build.gradle
- Plan/extensions/src/main/java/com/djrapitops/plan/extension/implementation/ExtensionRegister.java
- [ x] Make sure your name is added to Contributors file `/Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java`
- [ x] If PR:ing locale changes also add a LangCode with your name `/Plan/common/src/main/java/com/djrapitops/plan/settings/locale/LangCode.java`
Most of the work I did was for the extension itself and not this repo, that is why most of the explenation can be found [here](https://github.com/plan-player-analytics/Extension-template/pull/153)
Thank you!
> Added CMI-Extension

- .github/workflows/on-release.yml
- Plan/fabric/build.gradle
- Plan/fabric/src/main/resources/fabric.mod.json
> Update to Fabric 1.21.3 & fabric-permissions-api 0.3.3

- .github/workflows/ci.yml
Attempts a fix for ERR_NETWORK_CHANGED by disabling IPv6 from sysctl
Affects issues:
- #3535
> Disable IPv6 in Github Actions
